// Generated by tools/generate_config.py; edit schemas/config-v1.json.
#pragma once
#include <cstdint>
#include <string>
namespace settings {
struct Config {
    double shunt_uohm = 150;
    int32_t polarity = 1;
    double i_zero_uV = 0;
    double i_gain = 1;
    double u_zero_V = 0;
    double u_gain = 1;
    uint32_t requested_rate_hz = 50;
    uint32_t adc_range = 0;
    uint32_t vshunt_ct_code = 5;
    uint32_t vbus_ct_code = 5;
    uint32_t temp_ct_code = 5;
    uint32_t average_code = 0;
    uint32_t ready_timeout_us = 15000;
    uint32_t max_gap_us = 40000;
    uint32_t flush_interval_ms = 1000;
    uint32_t queue_bytes = 65536;
    uint32_t rotation_bytes = 1073741824;
    uint32_t reserve_bytes = 67108864;
    bool allow_unknown_utc = false;
    uint32_t display_hz = 5;
    uint32_t live_hz = 5;
    uint32_t display_filter_tau_ms = 0;
    int32_t display_utc_offset_min = 0;
    std::string calibration_id = "nominal-uncalibrated";
    std::string calibration_note = "";
    std::string calibration_utc = "";
    bool calibration_valid = false;
    uint32_t oled_contrast = 127;
};
}
