"""Reproducible offline device panel: one HTML asset for USB and ESP32 Flash."""
import gzip,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def build():
    ui=ROOT/'device_ui'
    html=(ui/'index.template.html').read_text(encoding='utf8')
    for key,value in {
        '/*STYLE*/':(ui/'style.css').read_text(encoding='utf8'),
        '/*SCHEMA*/':json.dumps(json.loads((ROOT/'schemas/config-v1.json').read_text(encoding='utf8'))['fields'],ensure_ascii=False,separators=(',',':')),
        '/*CODEC*/':(ui/'codec.js').read_text(encoding='utf8'),
        '/*RATE_PROFILE*/':(ui/'rate_profile.js').read_text(encoding='utf8'),
        '/*APP*/':(ui/'app.js').read_text(encoding='utf8'),
    }.items(): html=html.replace(key,value)
    data=html.encode('utf8');compressed=gzip.compress(data,compresslevel=9,mtime=0)
    (ui/'index.html').write_bytes(data)
    rows=[','.join('0x%02x'%n for n in compressed[p:p+24]) for p in range(0,len(compressed),24)]
    (ROOT/'firmware/include/panel_assets.h').write_text('// Generated by tools/build_panel.py; do not edit.\n#pragma once\n#include <Arduino.h>\nconst uint8_t PANEL_HTML[] PROGMEM = {\n'+',\n'.join(rows)+'\n};\n',encoding='utf8')
    print(f'Panel: {len(data)} HTML bytes, {len(compressed)} gzip bytes')
if __name__=='__main__':build()
