"""Generate firmware fields/validation/codec from the normative P1 registry."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
fields=json.loads((ROOT/'schemas/config-v1.json').read_text())['fields']
types={'u32':'uint32_t','i32':'int32_t','f64':'double','bool':'bool','utf8':'std::string'}
codes={'u32':1,'i32':2,'f64':3,'bool':4,'utf8':5}
def literal(v): return json.dumps(v,ensure_ascii=True)
lines=['// Generated by tools/generate_config.py; edit schemas/config-v1.json.','#pragma once','#include <cstdint>','#include <string>','namespace settings {','struct Config {']
for f in fields: lines.append(f"    {types[f['type']]} {f['name']} = {literal(f['default'])};")
lines+=['};','}']
(ROOT/'firmware/include/config_fields.h').write_text('\n'.join(lines)+'\n',encoding='utf8')
lines=['// Generated by tools/generate_config.py; included inside namespace settings.','bool validate(const Config& c) {']
for f in fields:
 n='c.'+f['name'];kind=f['type']
 checks=[]
 if kind=='utf8': checks=[f'{n}.size() <= {f["max_bytes"]}',f'utf8({n})']
 if kind=='f64':checks=[f'std::isfinite({n})']
 if 'min' in f:checks.append(f'{n} >= {literal(f["min"])}')
 if 'max' in f:checks.append(f'{n} <= {literal(f["max"])}')
 if 'enum' in f:checks.append('('+' || '.join(f'{n} == {literal(x)}' for x in f['enum'])+')')
 if f['name']=='requested_rate_hz':
  lines+=['#if R1_BENCHMARK','    if (c.requested_rate_hz < 1 || c.requested_rate_hz > 1000) return false;','#else']
 if checks:lines.append('    if (!('+' && '.join(checks)+')) return false;')
 if f['name']=='requested_rate_hz':lines.append('#endif')
lines+=['    return validDate(c.calibration_utc) && (!c.calibration_valid || (!c.calibration_id.empty() && !c.calibration_note.empty() && !c.calibration_utc.empty()));','}','Bytes encode(const Config& c) {','    Bytes out; if (!validate(c)) return out;']
for f in fields:lines.append(f"    append(out, {f['id']}, {codes[f['type']]}, c.{f['name']});")
lines+=['    return out;','}','bool decode(const Bytes& data, Config& result) {','    Config c; size_t pos=0;']
for f in fields:lines.append(f"    if (!take(data,pos,{f['id']},{codes[f['type']]},c.{f['name']})) return false;")
lines+=['    if (pos != data.size() || !validate(c)) return false;','    result=c; return true;','}']
(ROOT/'firmware/include/config_codec_generated.inc').write_text('\n'.join(lines)+'\n',encoding='utf8')
lines=['// Generated by tools/generate_config.py; included inside configJson.']
for i,f in enumerate(sorted(fields,key=lambda f:f['name'])):
 n='c.'+f['name']
 value=('jsonQuote('+n+')' if f['type']=='utf8' else 'std::string('+n+' ? "true" : "false")' if f['type']=='bool' else 'real('+n+')' if f['type']=='f64' else 'signedInteger('+n+')' if f['type']=='i32' else 'integer('+n+')')
 lines.append('s += '+json.dumps((',' if i else '')+'"'+f['name']+'":')+' + '+value+';')
(ROOT/'firmware/include/config_json_generated.inc').write_text('\n'.join(lines)+'\n',encoding='utf8')
